// ui_flow full cycle + double/long click on a fresh temp app (emulator).
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { evidence, mcp, record, waitJob } from "./lib.mjs";
const EMU = "127.0.0.1:5555";
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "audit-flow-"));
const P = path.join(tmp, "App");
const c = await mcp();
await c.call("project", { action: "create", project: P, app_name: "F", bundle_name: "com.devecomcp.flow", compatible_api: 24 });
const br = await waitJob(c, await c.call("run", { action: "build_run", project: P, target: EMU, wait: 60000 }));
const out = { build_run: br.status };
const step = async (k, tool, args, ok) => { const r = await c.call(tool, args); const d = r.data?.job_id && r.data.status === "running" ? await waitJob(c, r) : r.data; out[k] = d; const pass = ok(d, r.isError); record(`B.action.${k}`, pass ? "VERIFIED" : "DEFECT", pass ? "as expected" : `unexpected: ${JSON.stringify(d).slice(0, 200)}`, [evidence("actions", `${k}.json`, { args, data: d })]); return d; };
await step("ui.act.double_click.success", "ui", { action: "act", target: EMU, op: "double_click", selector: { text: "Hello World" } }, (d, e) => !e);
await c.call("run", { action: "launch", project: P, target: EMU });
await step("ui.act.long_click.success", "ui", { action: "act", target: EMU, op: "long_click", selector: { text: "Hello World" } }, (d, e) => !e);
await c.call("run", { action: "launch", project: P, target: EMU });
await step("ui_flow.record.success", "ui_flow", { action: "record", project: P, target: EMU, id: "audit-flow" }, (d, e) => !e && d.recording === "audit-flow");
await step("ui_flow.record.failure-conflict", "ui_flow", { action: "record", project: P, target: EMU, id: "audit-flow2" }, (d, e) => e && d.error.code === "CONFLICT");
await c.call("ui", { action: "act", target: EMU, op: "click", selector: { text: "Hello World" } });
await step("ui_flow.stop.success", "ui_flow", { action: "stop", project: P, target: EMU, assert: { visible: { text: "Welcome" } } }, (d, e) => !e);
await step("ui_flow.list.success", "ui_flow", { action: "list", project: P }, (d) => d.flows?.some((f) => f.id === "audit-flow" && f.steps >= 1));
await step("ui_flow.show.success", "ui_flow", { action: "show", project: P, id: "audit-flow" }, (d) => d.steps?.length >= 1);
await step("ui_flow.replay.success", "ui_flow", { action: "replay", project: P, target: EMU, id: "audit-flow", wait: 60000 }, (d) => d.status === "succeeded");
await step("ui_flow.delete.success", "ui_flow", { action: "delete", project: P, id: "audit-flow" }, (d, e) => !e && d.deleted === "audit-flow");
await step("ui_flow.delete.failure", "ui_flow", { action: "delete", project: P, id: "audit-flow" }, (d, e) => e && d.error.code === "NOT_FOUND");
await c.call("run", { action: "uninstall", project: P, target: EMU });
await c.close();
fs.rmSync(tmp, { recursive: true, force: true });
