import fs from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import { z } from "zod";
import { StateStore } from "./store.js";
import { captureFile, capturedFileSchema, verifyCapturedFile } from "./captured-file.js";
import { currentTrace } from "./trace.js";
import { atomicWrite, destinationPath, fileDigest, publishFile } from "./files.js";
import { invariant } from "./errors.js";

const privateReference = z.object({ artifact_id: z.string().uuid(), identity: z.string().uuid() });
export const publicationSchema = z.object({
  path: z.string(), sha256: z.string().regex(/^[a-f0-9]{64}$/), bytes: z.number().int().nonnegative(),
  content: z.discriminatedUnion("kind", [
    z.object({ kind: z.literal("private"), reference: privateReference }),
    z.object({ kind: z.literal("package"), reference: capturedFileSchema }),
  ]),
});
export type Publication = z.infer<typeof publicationSchema>;

/** Freeze generated bytes before publishing. Private keys/material never enter plaintext artifacts. */
export async function preparePublication(store: StateStore, source: string, output: string, secret: boolean, signal?: AbortSignal): Promise<Publication> {
  signal?.throwIfAborted();
  if (!secret) {
    const reference = await captureFile(store, currentTrace().run_id ?? "signing", source, undefined, signal);
    return { path: output, bytes: reference.bytes, sha256: reference.sha256, content: { kind: "package", reference } };
  }
  const fd = fs.openSync(source, fs.constants.O_RDONLY | fs.constants.O_NONBLOCK);
  try {
    const before = fs.fstatSync(fd);
    invariant(before.isFile() && before.size <= 16 * 1024 * 1024, "PRIVATE_FILE_TOO_LARGE", "Signing material must be a regular file of at most 16 MiB");
    const bytes = Buffer.alloc(before.size);
    try {
      let offset = 0;
      while (offset < bytes.length) {
        signal?.throwIfAborted();
        const count = fs.readSync(fd, bytes, offset, bytes.length - offset, offset);
        invariant(count > 0, "SIGN_OUTPUT_CHANGED", "Signing material was truncated during capture");
        offset += count;
      }
      const after = fs.fstatSync(fd);
      invariant(before.size === after.size && before.mtimeMs === after.mtimeMs && before.ctimeMs === after.ctimeMs && bytes.length === before.size, "SIGN_OUTPUT_CHANGED", "Signing material changed during capture");
      return { path: output, bytes: bytes.length, sha256: crypto.createHash("sha256").update(bytes).digest("hex"), content: { kind: "private", reference: store.privateBytes(bytes) } };
    } finally { bytes.fill(0); }
  } finally { fs.closeSync(fd); }
}

/** A present output must match the prepared bytes; an absent output can be safely republished. */
export async function completePublication(store: StateStore, prepared: Publication, signal?: AbortSignal) {
  signal?.throwIfAborted();
  invariant(destinationPath(prepared.path) === prepared.path, "SIGN_OUTPUT_PARENT_CHANGED", "Signing destination resolves to a different path");
  const stat = fs.lstatSync(prepared.path, { throwIfNoEntry: false });
  if (stat) {
    invariant(stat.isFile() && !stat.isSymbolicLink() && stat.size === prepared.bytes && fileDigest(prepared.path) === prepared.sha256, "SIGN_OUTPUT_CHANGED", "Signing publication differs from its recorded bytes");
    return { path: prepared.path, bytes: prepared.bytes, sha256: prepared.sha256 };
  }
  fs.mkdirSync(path.dirname(prepared.path), { recursive: true, mode: 0o700 });
  if (prepared.content.kind === "package") {
    await verifyCapturedFile(prepared.content.reference, signal);
    await publishFile(prepared.content.reference.path, prepared.path, signal);
  } else {
    const bytes = store.openPrivateBytes(prepared.content.reference);
    try {
      invariant(bytes.length === prepared.bytes && crypto.createHash("sha256").update(bytes).digest("hex") === prepared.sha256, "SIGN_OUTPUT_CHANGED", "Private signing publication is corrupt");
      atomicWrite(prepared.path, bytes, false);
    } finally { bytes.fill(0); }
  }
  return { path: prepared.path, bytes: prepared.bytes, sha256: prepared.sha256 };
}
