import fs from "node:fs";
import path from "node:path";
import { release, packageRoot } from "../src/core/config.js";
import { atomicWrite, digest, fileDigest, inside } from "../src/core/files.js";
import { invariant } from "../src/core/errors.js";
import { z } from "zod";
import { readJson } from "./lib/upstream-adaptation.js";
import { releaseGate } from "./lib/release-gate.js";
import { sealDistribution } from "./lib/distribution.js";
const [action, input, receipt, output] = process.argv.slice(2);
invariant(action === "prepare" && input && receipt && output, "RELEASE_USAGE", "prepare MANIFEST RECEIPT NEW_DIRECTORY");
const manifestFile = path.resolve(input), directory = path.dirname(manifestFile), raw = readJson(manifestFile), checked = releaseGate(packageRoot, directory, raw);
const prior = z.object({ passed: z.literal(true), manifest_sha256: z.string(), distribution_sha256: z.string(), tested: z.object({ runtime_sha256: z.string() }) }).parse(readJson(receipt));
invariant(prior.manifest_sha256 === checked.manifest_sha256 && prior.distribution_sha256 === checked.distribution_sha256 && prior.tested.runtime_sha256 === checked.tested.runtime_sha256, "RELEASE_RECEIPT_CHANGED", "Gate receipt differs from fresh validation");
invariant(!fs.existsSync(output), "OUTPUT_EXISTS", "Use a new publish directory");
fs.mkdirSync(output, { recursive: true });
const manifest = z.object({ distribution: z.string() }).parse(raw), archive = path.join(output, `deveco-tool-${release}.zip`);
const sealed = sealDistribution(inside(directory, manifest.distribution), archive, path.join(packageRoot, "package-lock.json"));
invariant(sealed.manifest_sha256 === checked.distribution_sha256, "RELEASE_ARCHIVE_CHANGED", "Archive seal must preserve the accepted installation manifest");
atomicWrite(path.join(output, "acceptance.json"), JSON.stringify({ release, passed: true, runtime_sha256: checked.tested.runtime_sha256, manifest_sha256: digest(raw), distribution_sha256: checked.distribution_sha256, archive_sha256: fileDigest(archive), platforms: checked.regression, acceptance_cases: checked.acceptance_cases }, null, 2) + "\n", false);
if (process.env.GITHUB_OUTPUT) fs.appendFileSync(process.env.GITHUB_OUTPUT, `tag=v${release}\n`);
console.log(JSON.stringify({ directory: output, tag: `v${release}`, passed: true }));
