import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { kvGet, kvSet } from "../core/db.js";

/*
 * Incremental build preflight: the ArkTS static check only needs the sources edited since the last
 * preflight. Measured on LingDong (1,659 files): whole project 4.2-21.5 s, one file 0.4 s; the stat
 * walk below costs ~40 ms. Files that still had errors are not remembered, so they are re-checked.
 *
 * mtime alone is not enough: every hvigor build rewrites each module's generated BuildProfile.ets
 * (same content, new mtime). An entry is "mtime:size:sha1"; only files whose mtime/size moved are
 * re-hashed, and a file counts as changed only when its content differs.
 */

const skip = new Set(["node_modules", "oh_modules", "build", ".hvigor", ".git", ".idea", ".preview", ".arkpilot", "libs"]);
/** Generated by hvigor on every build, or build scripts: never application code to check. */
const generated = /(^|\/)(BuildProfile\.ets|hvigorfile\.ts|hvigorconfig\.ts)$/;
export type SourceSnapshot = Record<string, string>;

const hash = (file: string) => crypto.createHash("sha1").update(fs.readFileSync(file)).digest("hex").slice(0, 16);
const stamp = (entry: string | undefined) => entry?.split(":").slice(0, 2).join(":");
const content = (entry: string | undefined) => entry?.split(":")[2];

/**
 * Relative path -> "mtimeMs:size:sha1" of every .ets/.ts source. Hashes are reused from `previous`
 * while mtime and size are unchanged, so a steady state costs one stat per file.
 */
export function snapshotSources(root: string, previous: SourceSnapshot = {}): SourceSnapshot {
  const out: SourceSnapshot = {};
  const base = path.resolve(root);
  const stack = [base];
  while (stack.length) {
    const dir = stack.pop()!;
    let entries: fs.Dirent[];
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { continue; }
    for (const e of entries) {
      if (skip.has(e.name) || e.name.startsWith(".")) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) { stack.push(full); continue; }
      if (!/\.(ets|ts)$/.test(e.name) || e.name.endsWith(".d.ts")) continue;
      const rel = path.relative(base, full).replaceAll("\\", "/");
      if (generated.test(rel)) continue;
      try {
        const st = fs.statSync(full);
        const s = `${Math.floor(st.mtimeMs)}:${st.size}`;
        out[rel] = stamp(previous[rel]) === s && content(previous[rel]) ? previous[rel]! : `${s}:${hash(full)}`;
      } catch { /* vanished during the walk */ }
    }
  }
  return out;
}

/** Files added or whose content changed between two snapshots (deleted files need no check). Pure. */
export function diffSources(previous: SourceSnapshot, current: SourceSnapshot) {
  return Object.keys(current).filter((f) => content(previous[f]) !== content(current[f])).sort();
}

const key = (root: string) => `preflight:${path.resolve(root)}`;

/**
 * files=undefined: no baseline yet (first preflight) or too many edits to be worth scoping -> whole project.
 * files=[]: nothing changed since the last preflight.
 */
export async function changedSources(root: string, maxFiles = 200) {
  const raw = await kvGet(key(root)).catch(() => undefined);
  const previous = raw ? (JSON.parse(raw) as SourceSnapshot) : undefined;
  const snapshot = snapshotSources(root, previous);
  if (!previous) return { files: undefined, snapshot };
  const changed = diffSources(previous, snapshot);
  return { files: changed.length > maxFiles ? undefined : changed, snapshot };
}

/** Remember the checked state; files with errors are left out so the next preflight checks them again. */
export async function rememberSources(root: string, snapshot: SourceSnapshot, failing: string[] = []) {
  const kept = { ...snapshot };
  for (const f of failing) delete kept[f.replaceAll("\\", "/")];
  await kvSet(key(root), JSON.stringify(kept)).catch(() => undefined);
}
